apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  ports:
    - name: "http"
      port: 8006
      targetPort: 8006
  selector:
    app: chat-service
  type: ClusterIP