apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8006
      targetPort: 8006
  type: ClusterIP