apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  selector:
    app: file-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP