apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:26.0
          name: keycloak
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          args:
            - start-dev
            - --import-realm
          env:
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_DB_VENDOR
              value: h2
            - name: KC_HOSTNAME
              value: localhost
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/fitness-app-realm.json
              name: keycloak-cm0
              subPath: fitness-app-realm.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: fitness-app-realm.json
                path: fitness-app-realm.json
            name: keycloak-cm0
          name: keycloak-cm0
