apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabittmq
spec:
  selector:
    matchLabels:
      app: rabittmq
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4-management
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest