apiVersion: v1
kind: Service
metadata:
  name: rabittmq
spec:
  ports:
    - name: http
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  selector:
    app: rabittmq
  type: ClusterIP
