apiVersion: v1
kind: Service
metadata:
  labels:
    app: azurite
  name: azurite
spec:
  ports:
    - name: "http"
      port: 10000
      targetPort: 10000
  selector:
    app: azurite
  type: ClusterIP