apiVersion: v1
kind: Service
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  selector:
    app: azurite
  ports:
    - name: http
      port: 10000
      targetPort: 10000
  type: ClusterIP