apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: file-service
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: file-service
    spec:
      containers:
        - env:
            - name: ConnectionStrings__AzureStorageConnectionString
              value: AccountName=sentemon;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite:10000/sentemon
            - name: ConnectionStrings__DatabaseConnectionString
              value: Host=postgres;Port=5432;Username=postgres;Password=mysecretpasswordfordevelopment;Database=FileDb
            - name: RabbitMq__Host
              value: rabbitmq
          image: file-service
          livenessProbe:
            exec:
              command:
                - curl -f http://file-service:8004/health || exit 1
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          name: file-service
          ports:
            - containerPort: 8004
              protocol: TCP
      restartPolicy: Always
