apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: ReverseProxy__Clusters__auth-service__Destinations__destination1__Address
              value: http://auth-service:8001
            - name: ReverseProxy__Clusters__chat-service__Destinations__destination1__Address
              value: http://chat-service:8006
            - name: ReverseProxy__Clusters__file-service__Destinations__destination1__Address
              value: http://file-service:8004
            - name: ReverseProxy__Clusters__post-service__Destinations__destination1__Address
              value: http://post-service:8002
            - name: ReverseProxy__Clusters__workout-service__Destinations__destination1__Address
              value: http://workout-service:8005
          image: gateway
          livenessProbe:
            exec:
              command:
                - curl -f http://gateway:8000/health || exit 1
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          name: gateway
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
