apiVersion: v1
kind: Service
metadata:
  name: workout-service
  labels:
    app: workout-service
spec:
  selector:
    app: workout-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005
  type: ClusterIP