apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
spec:
  selector:
    matchLabels:
      app: workout-service
  template:
    spec:
      containers:
        - name: workout-service
          image: workout-service
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8005
          env:
            - name: DatabaseConnectionString
              value: Host=postgres;Port=5432;Username=postgres;Password=mysecretpasswordfordevelopment;Database=WorkoutsDb
            - name: RabbitMq__Host
              value: rabbitmq